export const ADD_CHANNEL = 'ADD_CHANNEL';
export const SELECT_CHANNEL = 'SELECT_CHANNEL';
export const REMOVE_CHANNEL = 'REMOVE_CHANNEL';

export const SELECT_BLOCK = 'SELECT_BLOCK';
export const UPDATE_BLOCKS = 'UPDATE_BLOCKS';

export const SELECT_ELE = 'SELECT_ELE';
export const EDIT_SELECTED_ELE = 'EDIT_SELECTED_ELE';
